Umniah-E-Sport.Tool/Controllers/CasualGameController.cs
using Umniah_E_Sport.Tool.Managers.Upload;
using Umniah_E_Sport.Tool.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Net.Http;
using System.Threading.Tasks;

namespace Umniah_E_Sport.Tool.Controllers
{
    public class CasualGameController : Controller
    {
        private readonly swaggerClient _swaggerClient;
        private readonly IUploadFileManager _fileManager;
        public CasualGameController(IUploadFileManager fileManager)
        {
            _swaggerClient = new swaggerClient("http://api.sltech.org/Zain-E-Sport/", new HttpClient());
            _fileManager = fileManager;
        }
        public async Task<IActionResult> Index()
        {
            var result = await _swaggerClient.GetAllCasualGamesAsync();
            return View(result);
        }
        public async Task<IActionResult> CreateAsync()
        {
            ViewBag.CasualCategories = await _swaggerClient.GetAllCasualCategoriesAsync();
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [RequestFormLimits(MultipartBodyLengthLimit = 409715200)]
        [RequestSizeLimit(409715200)]
        public async Task<IActionResult> CreateAsync(CreateCasualGameCommand command, IFormFile bannerImageFile,IFormFile ThumbnailImageFile)
        {
            try
            {
                if (bannerImageFile != null)
                {
                    command.BannerImageName = _fileManager.UploadCasualGameBannerImage(bannerImageFile);
                }
                if (ThumbnailImageFile != null)
                {
                    command.ThumbnailImageName = _fileManager.UploadCasualGameThumbnailImage(ThumbnailImageFile);
                }
                
                var model = await _swaggerClient.CreateCasualGameAsync(command);
                if (model.Success)
                    return RedirectToAction(nameof(Index));
                else return View();
            }
            catch
            {
                return View();
            }
        }
        public async Task<ActionResult> Details(int id)
        {
            var model = await _swaggerClient.GetCasualGameByIdAsync(id);
            return View(model);
        }

        public async Task<ActionResult> Edit(int id)
        {

            ViewBag.CasualCategories = await _swaggerClient.GetAllCasualCategoriesAsync();
            var model = await _swaggerClient.GetCasualGameByIdAsync(id);
            return View(model);
        }

        // POST: GameController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, UpdateCasualGameCommand command, IFormFile bannerImageFile, IFormFile ThumbnailImageFile)
        {
            try
            {
                if (bannerImageFile != null)
                {
                    command.BannerImageName = _fileManager.UploadCasualGameBannerImage(bannerImageFile);
                }
                if (ThumbnailImageFile != null)
                {
                    command.ThumbnailImageName = _fileManager.UploadCasualGameThumbnailImage(ThumbnailImageFile);
                }

                command.Id = id;
                var model = await _swaggerClient.UpdateCasaulGameAsync(command);
                if (model.Success)
                    return RedirectToAction(nameof(Index));
                else return View();
            }
            catch
            {
                return View();
            }
        }

        // GET: GameController/Delete/5
        public async Task<ActionResult> Delete(int id)
        {

            return View(await _swaggerClient.GetCasualGameByIdAsync(id));
        }

        // POST: GameController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id, int TempParam)
        {
            try
            {
                var model = await _swaggerClient.DeleteCasualGameAsync(id);
                if (model.Success)
                    return RedirectToAction(nameof(Index));
                else return RedirectToAction("Delete", new { id = id });
            }
            catch
            {
                return RedirectToAction("Delete", new { id = id });
            }
        }
    
}
}

Umniah-E-Sport.Tool/Controllers/CasualGameImagesController.cs
using Umniah_E_Sport.Tool.Managers.Upload;
using Umniah_E_Sport.Tool.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Net.Http;
using System.Threading.Tasks;

namespace Umniah_E_Sport.Tool.Controllers
{
    public class CasualGameImagesController : Controller
    {
        private readonly swaggerClient _swaggerClient;
        private readonly IUploadFileManager _fileManager;

        public CasualGameImagesController(IUploadFileManager fileManager)
        {
            _swaggerClient = new swaggerClient("http://api.sltech.org/Zain-E-Sport/", new HttpClient());
            _fileManager = fileManager;
        }

        public async Task<IActionResult> Index(int casualGameId)
        {
            var result = await _swaggerClient.GetCasualGameByIdAsync(casualGameId);
            return View(result);
        }
        public IActionResult Create(int casualGameId)
        {
            return View(new CreateCasualGameImageCommand { CasualGameId = casualGameId });
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [RequestFormLimits(MultipartBodyLengthLimit = 409715200)]
        [RequestSizeLimit(409715200)]
        public async Task<IActionResult> CreateAsync(CreateCasualGameImageCommand command, IFormFile imageFile)
        {
            try
            {
                if (imageFile != null)
                {
                    command.ImageName = _fileManager.UploadCasualGameImage(imageFile);
                }

                var model = await _swaggerClient.CreateCasualGameImageAsync(command);
                if (model.Success)
                    return RedirectToAction(nameof(Index),new {casualGameId = command.CasualGameId});
                else return View();
            }
            catch
            {
                return View();
            }
        }
        // POST: GameController/Delete/5
        public async Task<ActionResult> Delete(int id,int casualGameId)
        {
            var model = await _swaggerClient.DeleteCasualGameImageAsync(id);
            return RedirectToAction(nameof(Index), new { casualGameId = casualGameId });
        }
    }
}

Umniah-E-Sport.Tool/Views/CasualGame/Create.cshtml
@model Umniah_E_Sport.Tool.Models.CreateCasualGameCommand

<h4>CreateCasualGameCommand</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Title_EN" class="control-label"></label>
                <input asp-for="Title_EN" class="form-control" />
                <span asp-validation-for="Title_EN" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title_AR" class="control-label"></label>
                <input asp-for="Title_AR" class="form-control" />
                <span asp-validation-for="Title_AR" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description_EN" class="control-label"></label>
                <input asp-for="Description_EN" class="form-control" />
                <span asp-validation-for="Description_EN" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description_AR" class="control-label"></label>
                <input asp-for="Description_AR" class="form-control" />
                <span asp-validation-for="Description_AR" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GameLink" class="control-label"></label>
                <input asp-for="GameLink" class="form-control" />
                <span asp-validation-for="GameLink" class="text-danger"></span>
            </div>
            <div class="form-group" hidden>
                <label asp-for="BannerImageName" class="control-label"></label>
                <input asp-for="BannerImageName" class="form-control" />
                <span asp-validation-for="BannerImageName" class="text-danger"></span>
            </div>

            <div class="form-group">
              <label for="bannerImageFile" class="control-label">Banner Image</label>
                <input id="bannerImageFile" name="bannerImageFile" class="form-control" type="file" />
                <span for="bannerImageFile" class="text-danger"></span>
            </div>
            <div class="form-group" hidden>
                <label asp-for="ThumbnailImageName" class="control-label"></label>
                <input asp-for="ThumbnailImageName" class="form-control" />
                <span asp-validation-for="ThumbnailImageName" class="text-danger"></span>
            </div>

            <div class="form-group">
              <label for="ThumbnailImageFile" class="control-label">Thumbnail Image</label>
                <input id="ThumbnailrImageFile" name="ThumbnailImageFile" class="form-control" type="file" />
                <span for="ThumbnailImageFile" class="text-danger"></span>
            </div>

            <div class="form-group col-md-6" `>
                <label asp-for="FileType" class="control-label"></label>
                <select class="form-control" asp-for="FileType" asp-items="Html.GetEnumSelectList<FileTypeEnum>()">
                    <option>Please Select File Type......</option>
                </select>
                <span asp-validation-for="FileType" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsFreatured" /> @Html.DisplayNameFor(model => model.IsFreatured)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="ProvidingBy" class="control-label"></label>
                <input asp-for="ProvidingBy" class="form-control" />
                <span asp-validation-for="ProvidingBy" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="@Model.CasualCategoryId" class="control-label"></label>
                <select asp-for="@Model.CasualCategoryId"
                        class="form-control" required
                        asp-items="@(new SelectList(@ViewBag.CasualCategories,"Id", "Name_EN"))">

                    <option>Select Script...</option>
                </select>
                <span asp-validation-for="@Model.CasualCategoryId" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
}

Umniah-E-Sport.Tool/Views/CasualGame/Delete.cshtml
@model Umniah_E_Sport.Tool.Models.GetCasualGameByIdVm

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>GetCasualGameByIdVm</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title_EN)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title_EN)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description_EN)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description_EN)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GameLink)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GameLink)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BannerImageName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BannerImageName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ThumbnailImageName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ThumbnailImageName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FileType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FileType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsFreatured)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsFreatured)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProvidingBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProvidingBy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CasualCategoryId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CasualCategoryId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Umniah-E-Sport.Tool/Views/CasualGame/Details.cshtml
@model Umniah_E_Sport.Tool.Models.GetCasualGameByIdVm

<div>
    <h4>GetCasualGameByIdVm</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title_EN)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title_EN)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title_AR)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title_AR)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description_EN)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description_EN)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description_AR)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description_AR)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GameLink)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GameLink)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BannerImageName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BannerImageName)
            <div>
                <img src="~/Path/CasualGames/Banners/@Model.BannerImageName" />
            </div>
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ThumbnailImageName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ThumbnailImageName)
             <div>
                <img src="~/Path/CasualGames/Thumbnails/@Model.ThumbnailImageName" />
            </div>
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FileType)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FileType)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsFreatured)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsFreatured)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ProvidingBy)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ProvidingBy)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CasualCategoryId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CasualCategoryId)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new {  id = Model.Id  }) |
    <a asp-action="Index">Back to List</a>
</div>

Umniah-E-Sport.Tool/Views/CasualGame/Edit.cshtml
@model Umniah_E_Sport.Tool.Models.GetCasualGameByIdVm

<h4>GetCasualGameByIdVm</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title_EN" class="control-label"></label>
                <input asp-for="Title_EN" class="form-control" />
                <span asp-validation-for="Title_EN" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title_AR" class="control-label"></label>
                <input asp-for="Title_AR" class="form-control" />
                <span asp-validation-for="Title_AR" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description_EN" class="control-label"></label>
                <input asp-for="Description_EN" class="form-control" />
                <span asp-validation-for="Description_EN" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description_AR" class="control-label"></label>
                <input asp-for="Description_AR" class="form-control" />
                <span asp-validation-for="Description_AR" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GameLink" class="control-label"></label>
                <input asp-for="GameLink" class="form-control" />
                <span asp-validation-for="GameLink" class="text-danger"></span>
            </div>

            <div>
                <img src="~/Path/CasualGames/Banners/@Model.BannerImageName" />
            </div>
            <div class="form-group" hidden>
                <label asp-for="BannerImageName" class="control-label"></label>
                <input asp-for="BannerImageName" class="form-control" />
                <span asp-validation-for="BannerImageName" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label for="bannerImageFile" class="control-label">Banner Image</label>
                <input id="bannerImageFile" name="bannerImageFile" class="form-control" type="file" />
                <span for="bannerImageFile" class="text-danger"></span>
            </div>

            <div>
                <img src="~/Path/CasualGames/Thumbnails/@Model.ThumbnailImageName" />
            </div>
            <div class="form-group" hidden>
                <label asp-for="ThumbnailImageName" class="control-label"></label>
                <input asp-for="ThumbnailImageName" class="form-control" />
                <span asp-validation-for="ThumbnailImageName" class="text-danger"></span>
            </div>

            <div class="form-group">
              <label for="ThumbnailImageFile" class="control-label">Thumbnail Image</label>
                <input id="ThumbnailrImageFile" name="ThumbnailImageFile" class="form-control" type="file" />
                <span for="ThumbnailImageFile" class="text-danger"></span>
            </div>

            <div class="form-group col-md-6" `>
                <label asp-for="FileType" class="control-label"></label>
                <select class="form-control" asp-for="FileType" asp-items="Html.GetEnumSelectList<FileTypeEnum>()">
                    <option>Please Select File Type......</option>
                </select>
                <span asp-validation-for="FileType" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsFreatured" /> @Html.DisplayNameFor(model => model.IsFreatured)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="ProvidingBy" class="control-label"></label>
                <input asp-for="ProvidingBy" class="form-control" />
                <span asp-validation-for="ProvidingBy" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="@Model.CasualCategoryId" class="control-label"></label>
                <select asp-for="@Model.CasualCategoryId"
                        class="form-control" required
                        asp-items="@(new SelectList(@ViewBag.CasualCategories,"Id", "Name_EN"))">

                    <option>Select Script...</option>
                </select>
                <span asp-validation-for="@Model.CasualCategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
    await Html.RenderPartialAsync("_ValidationScriptsPartial");
}
}

Umniah-E-Sport.Tool/Views/CasualGame/Index.cshtml
@model IEnumerable<Umniah_E_Sport.Tool.Models.GetAllCasualGamesVm>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table id="example" class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Title_EN)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description_EN)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.GameLink)
            </th>
    
            <th>
                @Html.DisplayNameFor(model => model.IsFreatured)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProvidingBy)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CasualCategoryId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title_EN)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description_EN)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GameLink)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsFreatured)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProvidingBy)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CasualCategoryId)
            </td>
            <td>
                @Html.ActionLink("Images", "Index","CasualGameImages", new { casualGameId =item.Id  }) |
                @Html.ActionLink("Edit", "Edit", new {  id=item.Id  }) |
                @Html.ActionLink("Details", "Details", new {  id=item.Id  }) |
                @Html.ActionLink("Delete", "Delete", new {  id=item.Id  }) 
            </td>
        </tr>
}
    </tbody>
</table>

@section scripts
{
    <script src="~/lib/datatables/js/jquery.dataTables.min.js"></script>
    <script src="~/lib/datatables/js/dataTables.bootstrap4.min.js"></script>
    <script asp-append-version="true">
            $(document).ready(function () {
                $('#example').DataTable();
            });
    </script>
}