Umniah-E-Sport.Portal/Controllers/TermsAndConditionsController.cs
using Microsoft.AspNetCore.Mvc;
using Umniah_E_Sport.Portal.ActionFilter;
using Umniah_E_Sport.Portal.Models;
using System.Net.Http;
using System.Threading.Tasks;

namespace Umniah_E_Sport.Portal.Controllers
{
    [ServiceFilter(typeof(UserMailAuthenticationFilter))]
    public class TermsAndConditionsController : Controller
    {
        private readonly swaggerClient _swaggerClient;
        public TermsAndConditionsController(IConfiguration config)
        {
            _swaggerClient = new swaggerClient(config.GetValue<string>("SwaggerSetting:SwaggerApiUrl"), new HttpClient());
        }
        public async Task<IActionResult> Index(int tournamentId)
        {
            var termsAndConditions = await _swaggerClient.GetTermsAndConditionsAsync(tournamentId);
            var tournament = await _swaggerClient.GetTournamentAsync(tournamentId);
            var model = new TermsAndConditionsVm
            {
                Tournament = tournament,
                TermsAndConditions = termsAndConditions,
            };
            return View(model);
        }
    }
}

Umniah-E-Sport.Portal/Controllers/TournamentsController.cs
using Microsoft.AspNetCore.Mvc;
using Umniah_E_Sport.Portal.ActionFilter;
using Umniah_E_Sport.Portal.Models;
using System.Net.Http;
using System.Threading.Tasks;
using UI.Helper.Managers.Portal;

namespace Umniah_E_Sport.Portal.Controllers
{
   [ServiceFilter(typeof(UserMailAuthenticationFilter))]
    public class TournamentsController : Controller
    {
        private readonly swaggerClient _swaggerClient;
        private readonly IUserManagerCookie _cookieManager;
        public TournamentsController(IUserManagerCookie cookieManager,IConfiguration config)
        {
            _swaggerClient = new swaggerClient(config.GetValue<string>("SwaggerSetting:SwaggerApiUrl"), new HttpClient());
            //_swaggerClient = new swaggerClient("http://api.sltech.org/Jawwal-E-Sport/", new HttpClient());
            _cookieManager = cookieManager;
        }
        public async Task<IActionResult> Index()
        {
            var tournaments = await _swaggerClient.GetAllTournamentsAsync();
            return View(tournaments);
        }

        public async Task<IActionResult> Featured()
        {
            return View(await _swaggerClient.GetFeatureTournamentsAsync());
        }

        public async Task<IActionResult> Details(int tournamentId )
        {
            try
            {
                string email = _cookieManager.GetUserEmail();
                
                if (email != null)
                {
                    var response = await _swaggerClient.IsUserAlreadyJoinTournamentAsync(email, tournamentId);
                    if (response.Success && response.IsExist)
                    {
                        return View("LaunchGame", await TournamentDetails(tournamentId));
                    }
                }
            }
            catch (Exception ex) { }
            var model = await _swaggerClient.GetTournamentAsync(tournamentId);
            return View(model);
        }

        public async Task<IActionResult> Upcoming()
        {
            var email = _cookieManager.GetUserEmail();

            var upcomingTournaments = await _swaggerClient.GetUpcomingTournamentsAsync(email);

            return View(upcomingTournaments);

        }

        public async Task<IActionResult> Live()
        {
            var email = _cookieManager.GetUserEmail();

            var upcomingTournaments = await _swaggerClient.GetLiveTournamentsAsync(email);

            return View(upcomingTournaments);

        }

        public async Task<IActionResult> Finished()
        {
            var email = _cookieManager.GetUserEmail();

            var upcomingTournaments = await _swaggerClient.GetFinishedTournamentsAsync(email);

            return View(upcomingTournaments);

        }

        public async Task<IActionResult> ByGame(int gameId)
        {
            var model = await _swaggerClient.GetTournamentsByGameIdAsync(gameId);
            return View(model);
        }

        public async Task<IActionResult> MyTournaments()
        {
            UserTournamentsVM model = new UserTournamentsVM();
            var email = _cookieManager.GetUserEmail();

            model.UpcomingTournaments = await _swaggerClient.GetUpcomingTournamentsAsync(email);
            model.LiveTournaments = await _swaggerClient.GetLiveTournamentsAsync(email);
            model.FinishedTournaments = await _swaggerClient.GetFinishedTournamentsAsync(email);

            return View(model);
        }

        public async Task<IActionResult> JoinTournament(int TournamentId)
        {
            return View(await TournamentDetails(TournamentId));
        }

        [HttpPost]
        public async Task<IActionResult> RegisterUserTournaments(string userName, int tournamentId, string ingameId)
        {
            var msisdn = _cookieManager.GetUser();
            var email = _cookieManager.GetUserEmail();
            RegisteredUserTournmentsCommand command = new RegisteredUserTournmentsCommand
            {
                UserName = userName,
                TournamentId = tournamentId,
                IngameId = ingameId,
                Msisdn = msisdn,
                Email = email
            };
            var response = await _swaggerClient.JoinUserTournamentAsync(command);
            if (response.Success)
            {
                return RedirectToAction("ConfirmationSucsess", new { tournamentId = tournamentId });
            }
            return RedirectToAction(nameof(Index));
        }


        private async Task<GetTournamentVM> TournamentDetails(int tournamentId)
        {
            var tournament = await _swaggerClient.GetTournamentAsync(tournamentId);
            return tournament;
        }
        public async Task<IActionResult> ConfirmationSucsess(int tournamentId)
        {
            try
            {
                return View(await TournamentDetails(tournamentId));
            }
            catch(Exception ex) { }
            return View(await TournamentDetails(2002) );
        }

        public async Task<IActionResult> LaunchGame(int tournamentId)
        {

            var tournament = await TournamentDetails(tournamentId);
            return View(tournament);
        }

    }
}

Umniah-E-Sport.Portal/Views/TermsAndConditions/Index.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer localizer
@{
    var isEn = localizer["Lang"].Value == "en";
}

@model TermsAndConditionsVm

@{
    Layout = "_Layout";
}
 

     <!--End Header-->
        <div class="fs-18 mt-2">Umniah</div>
        <div class="fs-32 mt-2 ff-vf-bold line-1-1">
            @(isEn ? Model.Tournament.Title_EN : Model.Tournament.Title_AR)
        </div>

        <main class="main-container px-3">
            <div class="mt-3 text-secondary fs-16 ff-vf-bold">
        @localizer["RegistrationFeesMessagePart1"] @Model.Tournament.SubscriptionFee @localizer["RegistrationFeesMessagePart2"]
            </div>
            <div class="mt-2 fs-16 ff-vf-bold">
                @localizer["ConfirmMessage"]
            </div>

            <h2 class="ff-vf-bold fs-24 mt-4"> @localizer["TermsAndConditions"]</h2>

            <p class="mt-3">
                Far far away, behind the word mountains, far from the countries
                Vokalia and Consonantia, there live the blind texts. Separated they
                live in Bookmarksgrove right at the coast of the Semantics, a large
                language ocean. A small river named Duden flows by their place and
                supplies it with the necessary regelialia. It is a paradisematic
                country, in which roasted parts of sentences fly into your mouth. Even
                the all-powerful Pointing has no control about the blind texts it is
                an almost unorthographic life One day however a small line of blind
                text by the name of Lorem Ipsum decided to leave for the far World of
                Grammar. The Big Oxmox advised her not to do so, because there were
                thousands of bad Commas, wild Question Marks and devious Semikoli, but
                the Little Blind Text didn’t listen. She packed her seven versalia,
                put her initial into the belt and made herself on the way. When she
                reached the first hills of the Italic Mountains, she had a last view
                back on the skyline of her hometown Bookmarksgrove, the headline of
                Alphabet Village and the subline of her own road, the Line Lane.
                Pityful a rethoric question ran over her cheek. Far far away, behind
                the word mountains, far from the countries Vokalia and Consonantia,
                there live the blind texts. Separated they live in Bookmarksgrove
                right at the coast of the Semantics, a large language ocean. A small
                river named Duden flows by their place and supplies it with the
                necessary regelialia. It is a paradisematic country, in which roasted
                parts of sentences fly into your mouth. Even the all-powerful Pointing
                has no control about the blind texts it is an almost unorthographic
                life One day however a small line of blind text by the name of Lorem
                Ipsum decided to leave for the far World of Grammar. The Big Oxmox
                advised her not to do so, because there were thousands of bad Commas,
                wild Question Marks and devious Semikoli, but the Little Blind Text
                didn’t listen. She packed her seven versalia, put her initial into the
                belt and made herself on the way. When she reached the first hills of
                the Italic Mountains, she had a last view back on the skyline of her
                hometown Bookmarksgrove, the headline of Alphabet Village and the
                subline of her own road, the Line Lane. Pityful a rethoric question
                ran over her cheek.
            </p>

            <div class="mt-1 px-2">
                <label class="d-flex align-items-start justify-content-between" for="terms">
                    <input type="checkbox" name="terms" id="terms" onchange="enableBtn()" />
                    <div class="
								terms-checkbox
								d-flex
								align-items-center
								justify-content-center
							">
                        <svg class="d-none" xmlns="http://www.w3.org/2000/svg" width="10.667" height="8" viewBox="0 0 10.667 8">
                    <path id="checked" d="M0,68.783l3.653,3.66,7.014-7.007L9.66,64.443l-6.007,6-2.66-2.66Z" transform="translate(0 -64.443)" fill="#E0E43C" />
                        </svg>
                    </div>
                    <div class="ml-2 mt-n1">
                        I agree to Umniah Play Arena Tournaments terms and conditions
                    </div>
                </label>

                <button id="terms-btn" class="
							mt-5
							w-100
							btn
							bg-highlight
							ff-vf-bold
							fs-18
							text-primary
							br-0
							px-3
							p-2
						" disabled onclick="location.href='@Url.Action("JoinTournament", "Tournaments",new {tournamentId = @Model.Tournament.Id})'">
                    @localizer["JoinTournament"]
                </button>
            </div>
        </main>
    

    <script>
        function enableBtn() {
            const termsCheck = document.querySelector("#terms");
            const termsBtn = document.querySelector("#terms-btn");
            if (termsCheck.checked) {
                termsBtn.disabled = false;
            } else {
                termsBtn.disabled = true;
            }
        }
    </script>