Umniah-E-Sport.Tool/Controllers/ArenaController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Umniah_E_Sport.Tool.Managers.Upload;
using Umniah_E_Sport.Tool.Models;
using System.Net.Http;
using System.Threading.Tasks;

namespace Umniah_E_Sport.Tool.Controllers
{
    public class ArenaController : Controller
    {

        private readonly swaggerClient _swaggerClient;
        private readonly IUploadFileManager _fileManager;
        public ArenaController(IUploadFileManager fileManager)
        {
            _swaggerClient = new swaggerClient("http://api.sltech.org/Zain-E-Sport/", new HttpClient());
            _fileManager = fileManager;
        }
        // GET: ArenaController
        public async Task<ActionResult> Index()
        {
            var model = await _swaggerClient.GetAllArenasAsync();
            return View(model);
        }

        // GET: ArenaController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            var model = await _swaggerClient.GetArenaAsync(id);

            return View(model);
        }

        // GET: ArenaController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ArenaController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CreateArenaCommand command, IFormFile imageFile)
        {
            try
            {
                if (imageFile != null)
                {

                    command.ImageName = _fileManager.UploadArenaImage(imageFile);
                }
                var model = await _swaggerClient.CreateArenaAsync(command);
                if (model.Success)
                    return RedirectToAction(nameof(Index));
                else return View();
            }
            catch
            {
                return View();
            }
        }

        // GET: ArenaController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            var model = await _swaggerClient.GetArenaAsync(id);
            return View(model);
        }

        // POST: ArenaController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, UpdateArenaCommand command, IFormFile imageFile)
        {
            try
            {
                if (imageFile != null)
                {

                    command.ImageName = _fileManager.UploadArenaImage(imageFile);
                }
                command.Id = id;
                var model = await _swaggerClient.UpdateArenaAsync(command);
                if (model.Success)
                    return RedirectToAction(nameof(Index));
                else return View();
            }
            catch
            {
                return View();
            }
        }

        // GET: ArenaController/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            var model = await _swaggerClient.GetArenaAsync(id);
            return View(model);
        }

        // POST: ArenaController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id, DeleteArenaCommand command)
        {
            try
            {
                command.ArenaId = id;
                var model = await _swaggerClient.DeleteArenaAsync(command);
                if (model.Success)
                    return RedirectToAction(nameof(Index));
                else return View(id);
            }
            catch
            {
                return View();
            }
        }
    }
}

Umniah-E-Sport.Tool/Controllers/GameController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Umniah_E_Sport.Tool.Managers.Upload;
using Umniah_E_Sport.Tool.Models;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;

namespace Umniah_E_Sport.Tool.Controllers
{
    public class GameController : Controller
    {

        private readonly swaggerClient _swaggerClient;
        private readonly IUploadFileManager _fileManager;
        public GameController(IUploadFileManager fileManager)
        {
            _swaggerClient = new swaggerClient("http://api.sltech.org/Zain-E-Sport/", new HttpClient());
            _fileManager = fileManager;
        }
        // GET: GameController
        public async Task<ActionResult> Index()
        {
            var model = await _swaggerClient.GetAllGamesAsync();
            return View(model);
        }

        // GET: GameController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            var model = await _swaggerClient.GetGameAsync(id);
            return View(model);
        }

        // GET: GameController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: GameController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(AddGameCommand command, IFormFile imageFile)
        {
            try
            {
                if (imageFile != null)
                {

                    command.ImageName = _fileManager.UploadGameImage(imageFile);
                }
                command.CreationTimeStamp = System.DateTime.Now;
                var model = await _swaggerClient.AddGameAsync(command);
                if (model.Success)
                    return RedirectToAction(nameof(Index));
                else return View();
            }
            catch
            {
                return View();
            }
        }

        // GET: GameController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            var model = await _swaggerClient.GetGameAsync(id);
            return View(model);
        }

        // POST: GameController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, UpdateGameCommand command, IFormFile imageFile)
        {
            try
            {
                if (imageFile != null)
                {

                    command.ImageName = _fileManager.UploadGameImage(imageFile);
                }

                command.Id = id;
                var model = await _swaggerClient.EditGameAsync(command);
                if (model.Success)
                    return RedirectToAction(nameof(Index));
                else return View();
            }
            catch
            {
                return View();
            }
        }

        // GET: GameController/Delete/5
        public async Task<ActionResult> Delete(int id)
        {

            return View(await _swaggerClient.GetGameAsync(id));
        }

        // POST: GameController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id, DeleteGameCommand command)
        {
            try
            {
                command.Id = id;
                var model = await _swaggerClient.DeleteGameAsync(command);
                if (model.Success)
                    return RedirectToAction(nameof(Index));
                else return View();
            }
            catch
            {
                return View();
            }
        }
        public async Task<ActionResult> UserGames(int id)
        {
            var userGames = await _swaggerClient.GetUserGamesByUserIdAsync(id);
            return View(userGames);
        }
    }
}

Umniah-E-Sport.Tool/Controllers/NewsController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Umniah_E_Sport.Tool.Managers.Upload;
using Umniah_E_Sport.Tool.Models;
using System.Net.Http;
using System.Threading.Tasks;

namespace Umniah_E_Sport.Tool.Controllers
{
    public class NewsController : Controller
    {
        private readonly swaggerClient _swaggerClient;
        private readonly IUploadFileManager _fileManager;
        public NewsController(IUploadFileManager fileManager)
        {
            _swaggerClient = new swaggerClient("http://api.sltech.org/Zain-E-Sport/", new HttpClient());
            _fileManager = fileManager;
        }

        // GET: NewsController
        public async Task<ActionResult> Index()
        {
            return View(await _swaggerClient.GetAllNewsAsync());
        }

        // GET: NewsController/Details/5
        public async Task<ActionResult> Details(int id)
        {

            return View(await _swaggerClient.GetNewsAsync(id));
        }

        // GET: NewsController/Create
        public async Task<ActionResult> Create()
        {
            ViewBag.Games = await _swaggerClient.GetAllGamesAsync();
            return View();
        }

        // POST: NewsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(CreateNewsCommand command, IFormFile imageFile)
        {
            try
            {

                if (imageFile != null)
                {

                    command.ImageName = _fileManager.UploadNewImage(imageFile);
                }
                command.TimeStamp = System.DateTime.Now;
                var model = await _swaggerClient.CreateNewsAsync(command);
                if (model.Success)
                    return RedirectToAction(nameof(Index));
                else return View();
            }
            catch
            {
                return View();
            }
        }

        // GET: NewsController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            ViewBag.Games = await _swaggerClient.GetAllGamesAsync();
            return View(await _swaggerClient.GetNewsAsync(id));
        }

        // POST: NewsController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, UpdateNewsCommand command, IFormFile imageFile)
        {
            try
            {

                if (imageFile != null)
                {

                    command.ImageName = _fileManager.UploadNewImage(imageFile);
                }
                var model = await _swaggerClient.UpdateNewsAsync(command);
                if (model.Success)
                    return RedirectToAction(nameof(Index));
                else return View(id);
            }
            catch
            {
                return View();
            }
        }

        // GET: NewsController/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            return View(await _swaggerClient.GetNewsAsync(id));
        }

        // POST: NewsController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id, DeleteNewsCommand command)
        {
            try
            {
                command.Id = id;
                var model = await _swaggerClient.DeleteNewsAsync(command);
                if (model.Success)
                    return RedirectToAction(nameof(Index));
                else return View(id);
            }
            catch
            {
                return View();
            }
        }
    }
}

Umniah-E-Sport.Tool/Controllers/UserController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Umniah_E_Sport.Tool.Models;
using System.Net.Http;
using System.Threading.Tasks;

namespace Umniah_E_Sport.Tool.Controllers
{
    public class UserController : Controller
    {
        private readonly swaggerClient _swaggerClient;
        public UserController()
        {
            _swaggerClient = new swaggerClient("http://api.sltech.org/Zain-E-Sport/", new HttpClient());
        }
        // GET: UserController
        public async Task<ActionResult> Index()
        {
            var users = await _swaggerClient.GetAllUsersOrderedByScoreAsync();
            return View(users);
        }
    }
}

Umniah-E-Sport.Tool/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity

@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Umniah_E_Sport.Tool</title>
    <link rel="stylesheet" href="~/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/line-awesome.min.css" />
    <link rel="stylesheet" href="~/css/helpers.css" />
    <link rel="stylesheet" href="~/css/style.css" />
    @*<link href="~/lib/datatables/css/jquery.dataTables.min.css" rel="stylesheet" />*@
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.22/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.6.4/css/buttons.dataTables.min.css" />
</head>
<body>
    <div class="body-layout">
        <!-- BEGIN: Header -->
        <nav class="navbar navbar-expand-lg fixed-top d-flex justify-content-between box-shadow-2 px-lg-4 px-2 py-0">
            <!-- bar and brand  -->
            <div class="d-flex justify-content-between align-items-center">
                @if (SignInManager.IsSignedIn(User))
                {
                    <div class="bar">
                        <a class="icon-toggle-side-menu primary-text fs-15 cursor-pointer">
                            <i class="las la-bars fs-30 primary-text"></i>
                        </a>
                    </div>
                }
                <a asp-controller="Home" asp-action="Index" class="navbar-brand p-0">
                    <!-- Logo -->
                    <div class="d-flex align-items-center">
                        <img src="/Umniah-e-sport/Resources/images/smart-logo.png" class="ml-lg-4 mx-2 mr-lg-3 d-inline-block sm-logo" width="180"
                             height="40">
                        <span class="d-inline-block fs-20">Umniah E Sport</span>
                    </div>
                </a>
            </div>
            <ul class="d-flex justify-content-between align-items-center list-unstyled mb-0">
                <!-- profile dropdown  -->
                <li class="nav-item dropdown px-3 profile-dropdown">
                    <div class="nav-link dropdown-toggle p-0 primary-text cursor-pointer" id="navbarDropdown" role="button"
                         data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <img src="~/Resources/images/businessman.png" width="50" height="50" alt=""
                             class="rounded-circle mx-2 align-bottom " style="background-color: #e78c85;">
                    </div>
                    <div class="dropdown-menu p-0 border-0 box-shadow-1 py-2" aria-labelledby="navbarDropdown">
                        <div class="d-flex justify-content-start align-items-center position-relative profile-info py-0">
                            <img src="~/Resources/images/businessman.png" width="40" height="40" alt="" class="rounded-circle mx-2"
                                 style="background-color: #e78c85;">
                            <div class="text-left">
                                Hello @UserManager.GetUserName(User)!
                            </div>
                        </div>
                        <div class="dropdown-divider"></div>
                        <partial name="_LoginPartial" />
                    </div>
                </li>
            </ul>
        </nav>

        <!-- END: Header -->
        <div class="main">
            <!-- BEGIN: SIDE-MENU -->
            <div class="sidebar h-100" id="sidebar">
                <div class="pb-4">
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <ul class="list-unstyled px-0 pt-3 m-0">
                            <li class="position-relative">
                                <a class="menu-item menu-link cursor-pointer" asp-area="" asp-controller="Arena" asp-action="Index">
                                    <i class="menu-icon las la-server"></i>
                                    <span class="nav-label fs-14">Arenas</span>
                                </a>
                            </li>
                            <li class="position-relative">
                                <a class="menu-item menu-link cursor-pointer" asp-route-id="" asp-controller="Game" asp-action="Index">
                                    <i class="menu-icon las la-server"></i>
                                    <span class="nav-label fs-14">Games</span>
                                </a>
                            </li>
                            <li class="position-relative">
                                <a class="menu-item menu-link cursor-pointer" asp-route-id="" asp-controller="Tournament" asp-action="Index">
                                    <i class="menu-icon las la-server"></i>
                                    <span class="nav-label fs-14">Tournaments</span>
                                </a>
                            </li>
                            <li class="position-relative">
                                <a class="menu-item menu-link cursor-pointer" asp-area="" asp-controller="Location" asp-action="Index">
                                    <i class="menu-icon las la-server"></i>
                                    <span class="nav-label fs-14">Locations</span>
                                </a>
                            </li>
                            <li class="position-relative">
                                <a class="menu-item menu-link cursor-pointer" asp-area="" asp-controller="TournamentType" asp-action="Index">
                                    <i class="menu-icon las la-server"></i>
                                    <span class="nav-label fs-14">Tournament Type</span>
                                </a>
                            </li>
                            <li class="position-relative">
                                <a class="menu-item menu-link cursor-pointer" asp-area="" asp-controller="UploadUsersTournamentScoreCSV" asp-action="Index">
                                    <i class="menu-icon las la-server"></i>
                                    <span class="nav-label fs-14">Upload User Tournament Score</span>
                                </a>
                            </li>
                            <li class="position-relative">
                                <a class="menu-item menu-link cursor-pointer" asp-area="" asp-controller="User" asp-action="Index">
                                    <i class="menu-icon las la-server"></i>
                                    <span class="nav-label fs-14">Users</span>
                                </a>
                            </li>
                            <li class="position-relative">
                                <a class="menu-item menu-link cursor-pointer" asp-area="" asp-controller="News" asp-action="Index">
                                    <i class="menu-icon las la-server"></i>
                                    <span class="nav-label fs-14">News</span>
                                </a>
                            </li>
                            <li class="position-relative">
                                <a class="menu-item menu-link cursor-pointer" asp-area="" asp-controller="Video" asp-action="Index">
                                    <i class="menu-icon las la-server"></i>
                                    <span class="nav-label fs-14">Videos</span>
                                </a>
                            </li>
                            <li class="position-relative">
                                <a class="menu-item menu-link cursor-pointer" asp-area="" asp-controller="CasualCategory" asp-action="Index">
                                    <i class="menu-icon las la-server"></i>
                                    <span class="nav-label fs-14">Casual Category</span>
                                </a>
                            </li>
                            <li class="position-relative">
                                <a class="menu-item menu-link cursor-pointer" asp-area="" asp-controller="CasualGame" asp-action="Index">
                                    <i class="menu-icon las la-server"></i>
                                    <span class="nav-label fs-14">Casual Games</span>
                                </a>
                            </li>
                        </ul>
                    }
                </div>
            </div>
            <!-- End: SIDE-MENU -->
            <!-- Page Content -->
            <div class="content p-3"> @RenderBody()</div>
            <!-- End: Content -->
        </div>
    </div>

    @*Loading OverLay*@
    <div class="overlay"></div>
    <div class="spanner">
        <div class="loader"></div>
        @*<p>Uploading file, please be patient.</p>*@
    </div>
    @*<script src="~/js/jquery-3.3.1.min.js"></script>*@
    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/custom.js"></script>
    <script src="https://cdn.datatables.net/1.10.22/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.4/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.4/js/buttons.flash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    @*<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>*@
    <script src="~/lib/pdfmake/pdfmake.min.js"></script>
    @*<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>*@
    <script src="~/lib/pdfmake/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.4/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.6.4/js/buttons.print.min.js"></script>





    <script asp-append-version="true">
        pdfMake.fonts = {
            Roboto: {
                normal: 'Janna-LT-Bold.ttf',
                bold: 'Janna-LT-Bold.ttf',
                italics: 'Janna-LT-Bold.ttf',
                bolditalics: 'Janna-LT-Bold.ttf'
            }
        };

        $(document).ready(function () {
            $('#example').DataTable({

                dom: 'Bfrtip',
                buttons: [
                    {
                        extend: 'copyHtml5',
                        exportOptions: {
                        }
                    },
                    {
                        extend: 'excelHtml5',
                        exportOptions: {
                        }
                    },
                    {
                        extend: 'pdfHtml5',
                        orientation: 'landscape',
                        exportOptions: {
                            orthogonal: "myExport"
                        }
                    },
                    {
                        extend: 'print',
                    }
                ]
            });
        });
    </script>



    @RenderSection("Scripts", required: false)
</body>
</html>